baseURL = "https://christopheducamp.com/"
languageCode = "fr"
title = " I Wanna Be a Sailor"
author = "christophe ducamp"
DefaultContentLanguage = "fr"
copyright = "Creative Commons Attribution 4.0 International License"
googleanalytics = "UA-104942350-1"
metaDataFormat = "yaml"

[permalinks]
  post = "/:year/:month/:day/:slug/"
[taxonomies]
  category = "categories"
  tag = "tags"
[sitemap]
  changefreq = "weekly"
 priority = 0.5

canonifyURLs = true ## Transforme toutes les URLs en absolues en utilisant baseURL
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
pygmentsUseClasses = true
pygmentCodeFences = true
#pygmentsStyle = "friendly"
#disqusShortname = "xtof"
#googleAnalytics = "XXX"


[params]
  name = "christophe ducamp"
  authorurl = "https://christopheducamp.com"
  author    = "christophe ducamp"
  handle    = "xtof"
  subtitle  = "sur la route de l'indieweb"
  summary   = "sur la route de l'indieweb"
  keywords  = "indieweb, web"
  description = "sur la route de l'indieweb"
  logo      = "/img/logo.jpg"
  twitter   = "https://twitter.com/xtof_party"
  facebook  = "https://www.facebook.com/christophe.ducamp"
  github    = "https://github.com/ChristopheDucamp/"
  gitlab    = "https://gitlab.com/ChristopheDucamp/"
  microblog = "https://micro.blog/xtof"
  instagram = "https://www.instagram.com/xtof_fr"
  #mastodon  = "https://indieweb.me/xtof"
  email     = "christophe@ducamp.me"
  keybase   = "https://keybase.io/christopheducamp"
  #licenseURL  = "/mentions-legales/"
  #stylesheetURL = "/css/style.min.css"
  #highlightJSURL = "/css/highlight.pack.js"
  newContentEditor = "bbedit"

## repo Gh pour le pied de page (inclure un slash ? la fin)
  ghrepo = "https://github.com/ChristopheDucamp/xtof-hugo-zen/"
  favicon = "img/favicon.ico"
  commit = "https://github.com/ChristopheDucamp/xtof-hugo-zen/tree"
  rss = true

 [Author]
     twitter ="xtof_party"

# MARKDOWN
## Configuration pour le parseur mardown BlackFriday : https://github.com/russross/blackfriday
[blackfriday]
 plainIDAnchors = true
 hrefTargetBlank = true
 angledQuotes = true
 smartypantsQuotesNBSP = true
 latexDashes = true



# Configuration Algolia

# [outputFormats.Algolia]
# baseName = "algolia"
# isPlainText = true
# mediaType = "application/json"
# notAlternative = true

# [params.algolia]
# vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
# params = ["categories", "tags"]


# [outputs]
# home = ["HTML", "RSS", "Algolia"]



